### ISSUE TITLE
Clarify where should [Test code] in the portfolio link to?

### ISSUE THREAD

**Issue by Tsuweiquan** [nusCS2113-AY1819S1/forum#101]
I would like to clarify where should [Test code] link to?
![image](https://user-images.githubusercontent.com/7202228/48059697-d5cc3580-e1f4-11e8-9716-2af6215b8f95.png)

[Functional code] links to repo sense but what about [Test code]?

**Comment by okkhoy** [comment]
Reposense reports both functional and testcode.
It is covered by this point:

![image](https://user-images.githubusercontent.com/1023494/48060106-f34dcf00-e1f5-11e8-87b2-a8b2336dbe20.png)

**Comment by Tsuweiquan** [comment]
Alright! So i can just remove [Test Code], as long as my [Functional code] links to the reposense.
Thank You Prof!

**Comment by okkhoy** [comment]
What do you mean you can remove [Test Code]?
The instructions indicate that "ignore minor enhancements and link to code from the sample template".
Reason:
1. We expect you to implement one feature, no concept of minor or major (that used to be the case in CS2103 a couple of semesters ago)
2. The code is already a part of the contribution summary earlier in the document where you link to reposense dashboard.

So there is no reason for you to retain those 2 lines from the template in your PPP. 
Could you please let me know the cause of confusion, so that I can tweak the instructions (if it is appropriate).

**Comment by Tsuweiquan** [comment]
Oh this is what i meant by removing [Test Code]
![image](https://user-images.githubusercontent.com/7202228/48061117-db2b7f00-e1f8-11e8-9246-bf0e2651a705.png)

I understand what you mean now. I have misread this sentence  `Follow the example in the AddressBook-Level4, but ignore the following two lines in it.` 
I should not include both Minor Enhancement & Code Contributedi in the PPP. Sorry for the confusion!
