### ISSUE TITLE
 Travis throws an exception: java.awt.HeadlessException

### ISSUE THREAD

**Issue by DarylTew** [nusCS2113-AY1819S1/forum#105]
So even though my CurrentCommandTest (my command is called Current) runs and passes on Intellij, Travis throws me an error:   java.awt.HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it.
See below:
![image](https://user-images.githubusercontent.com/34118159/48121108-0670a580-e2af-11e8-91ce-003cf126fbff.png)

This is how my code is:
![image](https://user-images.githubusercontent.com/34118159/48121120-0d97b380-e2af-11e8-8f75-f5e8c80c34b6.png)

Does anyone know how to fix this?

**Comment by okkhoy** [comment]
@DarylTew did you manage to get this working?

**Comment by DarylTew** [comment]
No I can't unfortunately. This only occurs for the tests when there is a success outcome.

**Comment by damithc** [comment]
Does the test work when run using gradle, in headless, mode on your computer?

**Comment by DarylTew** [comment]
The test works using gradle i think.

**Comment by pyokagan** [comment]
Some background information:

* Travis doesn't run an X server, so any GUI functionality won't work.

* In that case: how `headless` works is that TestFx installs a "mock" platform driver (called [Monocle](https://wiki.openjdk.java.net/display/OpenJFX/Monocle)). This platform driver makes JavaFX think it is creating windows, moving the mouse etc. without actually creating windows, moving the mouse etc, which is why it works on Travis. However it only works for *JavaFX*. In this case you are using Swing.

So you have two options:

1. Make Travis run an X server (search for xvfb). Note that this is by definition not "headless" according to AB-4's definition since you *are* actually creating windows, moving the mouse etc.

2. Follow TestFX's "headless" approach and mock out any GUI operations.

**Comment by pyokagan** [comment]
Alternatively, stick to JavaFX and not use Swing.

**Comment by DarylTew** [comment]
![image](https://user-images.githubusercontent.com/34118159/48253438-3308f680-e442-11e8-8ee5-2bd12338e60f.png)
Hi thanks for your reply, are you referring to this for option 1? And what do you mean by your note?

**Comment by DarylTew** [comment]
Oh and do you know why this happens only at this test? Surely there are other tests which are quite similar?

**Comment by yamgent** [comment]
> Hi thanks for your reply, are you referring to this for option 1?

Most likely yes.

> And what do you mean by your note?

By default, Travis is set up to run in headless mode (see the executed command inside `.travis.yml`):

```bash
travis_retry ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidoctor copyDummySearchPage
```

If you were to configure Travis to use xvfb, then you are techincally no longer using headless. I am not sure whether this requires you to turn headless mode off for Travis (turning on xvfb may not have an effect otherwise), so you will have to play around with it and give it a try.

> Oh and do you know why this happens only at this test? Surely there are other tests which are quite similar?

I only had a quick glance at your team's repo, so I may be wrong, but as far as I can tell, `CurrentCommand` is the only class around that are using `awt` and `swing` stuff. Everything else is using `javafx`.

If time permits, or if the xvfb is not working as expected and you really need it to work on Travis, I suggest re-looking at the implementation of `CurrentCommand`.

**Comment by DarylTew** [comment]
Thank you all for your help!
