### ISSUE TITLE
[Help Required] Travis-CI bug

### ISSUE THREAD

**Issue by LimYiSheng** [nusCS2113-AY1819S1/forum#40]
Hi everyone, my team has faced a Travis-CI mismatch on our PR towards CS2113's AB4 and on our own organisation repository. Travis-CI has showed a failed build on our PR towards CS2113's AB4, however, Travis-CI passed on our organisation repository. 

Some of the errors flagged out on the PR are shown in the screenshot below: 
![image](https://user-images.githubusercontent.com/35759184/46583427-9ab9d380-ca89-11e8-86cc-cf95ab020ea3.png) 

Other errors include trailing white space, however, we have checked all the files flagged by Travis-CI and they do not have the stated trailing white space. 

Some fixes and test my team has tried includes the following:
 - Temporary removal of AboutUs.adoc yet Travis-CI still flags that there is error in AboutUs.adoc when it is removed. 
 - Closed & Reopening of stated PR
 - Created PRs from our own personal repository towards CS2113's AB4 and Travis-CI actually passed for these PRs (the files on our personal repository and organisation repository are exactly the same) 

Does anyone know of any fix to this issue? 
Link to PR: https://github.com/nusCS2113-AY1819S1/addressbook-level4/pull/4
Link to Organisation Repository commits (with Travis-CI showing successful build): https://github.com/CS2113-AY1819S1-T16-4/main/commits/master

**Comment by okkhoy** [comment]
This could be an issue with the line ending settings of git.
Try this: https://help.github.com/articles/dealing-with-line-endings/

**Comment by zhihong8888** [comment]
<img width="947" alt="bug found" src="https://user-images.githubusercontent.com/35754191/46593823-8addd600-cb01-11e8-9d54-5ba671c1a720.png">

This line is causing the bug in our travis build, but we aren't sure how can we change this. Our pull request number is 4, not 49. It should be "$ git fetch origin +refs/pull/**4**/merge:" instead of "$ git fetch origin +refs/pull/**49**/merge"

Which also explains why our repo is having the same error as pull request 49

Is there any way we can solve this? Should we close this current pull and re-open a new one to get a new pull request number? 

Link to our repo: https://github.com /nusCS2113-AY1819S1/addressbook-level4/pull/4
Link to wrong repo: https://github.com  /nusCS2113-AY1819S1/  addressbook-level4/pull/49

**Comment by pyokagan** [comment]
> Should we close this current pull and re-open a new one to get a new pull request number?

Yes. This has happened before in previous semesters.

**Comment by LimYiSheng** [comment]
> Yes. This has happened before in previous semesters.

The issue has been resolved after getting a new pull request number, thank you for the help!
