### ISSUE TITLE
[Assistance Required] Travis build failure

### ISSUE THREAD

**Issue by LimYiSheng** [nusCS2113-AY1819S1/forum#62]
Hi everyone,

I came across an issue where my pull request fails Travis but passes Appveyor. Additionally, i tested the test file flagged by Travis locally on intellij and the JUnit test passes. The screenshot below shows the test failure flagged out by Travis: 
![image](https://user-images.githubusercontent.com/35759184/47269723-88b15800-d594-11e8-9d0c-aad0bc7b538d.png)

and the following screenshot is the test result of my PR:
![image](https://user-images.githubusercontent.com/35759184/47269727-9535b080-d594-11e8-9609-c2dee8a0f37e.png)

I am unsure how i can proceed to resolve this issue or bug because i can't seem to replicate it locally as the junit test passes on my intellij. Additionally, no changes were made to this test file. Would be glad if anyone could provide me some insights on how i could either replicate this bug or resolve it. Thanks! 

Link to my PR: https://github.com/CS2113-AY1819S1-T16-4/main/pull/117

**Comment by 0WN463** [comment]
If I'm correct, Travis uses a UNIX-based system while appveyor using a Windows-based system, which may explain the discrepancy there. If you have a groupmate with a Mac, you can try debugging there

**Comment by nianfei97** [comment]
Our group encountered this problem as well, it turned out to be a problem with a null pointer exception somewhere that was caught on travis but not on our local machine.

In the file `.travis.yml`, try updating the line in `script:` to read `travis_retry ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidoctor copyDummySearchPage --info` (add the `--info`) to get a more verbose log on travis, maybe it'll help you isolate your problem.

For reference, our PR that failed with a similar problem:
Without `--info`: https://travis-ci.org/CS2113-AY1819S1-W13-1/main/builds/442146060
With `--info`: https://travis-ci.org/CS2113-AY1819S1-W13-1/main/builds/442216933 (note line 1656 in the log)

Hope this helps you resolve your problem!

**Comment by arjo129** [comment]
Using `./gradlew headless tests` did the trick for me.

**Comment by LimYiSheng** [comment]
Thanks guys for the assistance! It seems like github isn't really functional today and i can't run my PRs properly, will try out the methods given above to resolve the issue! 

As to @arjo129, i tried running headless tests but it doesn't seem to be working on my end, not sure if it's because i'm using JDK10 instead of JDK9.
